export enum APP_ROUTES {
  INICIAR_DIAGNOSTICO = "/iniciar-diagnostico",
  REGISTRO_EMPRESAS = "/registro",
  PERFIL_EMPRESAS = "/registro/perfil-empresas",
  LOGIN = "/login",
  REGISTRO_LOGIN = "/login/registro",
  EMPRESAS_REGISTRADAS = "/registro/empresas-registradas",
  MIS_EMPRESAS = "/mis_empresas",
  CUENTIONARIOS = "/cuestionarios",
  CUESTIONARIO_CULTURA_DIGITAL = "/cuestionarios/cultura_digital",
  CUESTIONARIO_TECNOLOGIA_INFRAESTRUCTURA = "/cuestionarios/tecnologia_infraestructura",
  CUESTIONARIO_PROCESOS_AUTOMATIZACION = "/cuestionarios/procesos_automatizacion",
  CUESTIONARIO_DATOS_ANALITICA = "/cuestionarios/datos_analitica",
  CUESTIONARIO_EXPERIENCIA_CLIENTE = "/cuestionarios/experiencia_cliente",
  CUESTIONARIO_GOBERNANZA_SOSTENIBILIDAD = "/cuestionarios/gobernanza_sostenibilidad",
  CUESTIONARIO_PRESENCIA_REDES = "/cuestionarios/presencia_redes_sociales",
  CUESTIONARIO_CALIDAD_CIBERSEGURIDAD = "/cuestionarios/calidad_ciberseguridad",
}
